version: "3.8"

services:
  back:
    build: ./backend
    image: spring-add-img:v1
    container_name: Spring-boot-app
    restart: on-failure
    networks:
      - backend
    ports:
      - 8080:8080
    volumes:
      - .m2:/root/.m2
    depends_on:
      db:
        condition: service_healthy
  
  front:
    build: ./frontend
    image: vuejs-app-img:v1
    container_name: VueJS-app
    restart: on-failure
    networks:
      - frontend
    ports:
      - 8081:8080
    depends_on:
      - back
  
  db:
    image: mysql:8.0
    container_name: Database-app
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 40

networks:
  backend:
  frontend:

volumes:
  db: